import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'public');
const PORT=Number(process.env.PORT||8787); const HOST='0.0.0.0';
const MAX_Q=Number(process.env.ALS_MAX_SEARCH_LENGTH||180); const MAX_URL=Number(process.env.ALS_MAX_URL_LENGTH||2048);
const RATE_MAX=Number(process.env.ALS_RATE_MAX||90), RATE_WINDOW=Number(process.env.ALS_RATE_WINDOW_MS||60000); const buckets=new Map();
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
function headers(extra={}){return {'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Cross-Origin-Resource-Policy':'same-origin','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://itunes.apple.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'",'X-Robots-Tag':'noindex, nofollow, noarchive',...extra};}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,headers({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':Buffer.byteLength(body)}));res.end(body);}
function rate(req){const ip=req.socket.remoteAddress||'x',now=Date.now();let b=buckets.get(ip);if(!b||now-b.t>RATE_WINDOW)b={t:now,n:0};b.n++;buckets.set(ip,b);return b.n<=RATE_MAX;}
function clean(v=''){return String(v).trim().slice(0,MAX_Q);} function norm(s=''){return String(s).normalize('NFKC').toLowerCase().replace(/[\s\-_.・･:'"“”‘’()[\]{}\/\\]+/g,'');}
function same(a,b){if(!a||!b)return true;const x=norm(a),y=norm(b);return x===y||x.includes(y)||y.includes(x);} function eid(kind,id,c='JP'){return `itunes:${kind}:${Buffer.from(`${c}|${id}`).toString('base64url')}`;}
function pid(id=''){const m=String(id).match(/^itunes:[a-z]+:(.+)$/i);if(!m)return {country:'JP',id};try{const s=Buffer.from(m[1],'base64url').toString();const n=s.match(/^([A-Z]{2})\|(.+)$/i);return n?{country:n[1].toUpperCase(),id:n[2]}:{country:'JP',id:s};}catch{return {country:'JP',id};}}
async function ijson(endpoint,params,countries=['JP','US']){let last={results:[]};for(const country of countries){const u=new URL(`https://itunes.apple.com${endpoint}`);for(const [k,v] of Object.entries({...params,country}))u.searchParams.set(k,v);const r=await fetch(u,{headers:{'User-Agent':'ARTIST-LIVE-SHEET/0.6-beta'}});if(!r.ok)continue;last=await r.json();if((last.results||[]).length)return {d:last,country};}return {d:last,country:countries[0]};}
async function search(kind,q,artist=''){const entity=kind==='artist'?'musicArtist':kind==='album'?'album':'song',term=[artist,q].filter(Boolean).join(' ');const {d,country}=await ijson('/search',{term,media:'music',entity,limit:'40',lang:'ja_jp'});const rows=d.results||[];if(kind==='artist')return rows.filter(x=>x.artistId&&x.artistName).map(x=>({id:eid('artist',x.artistId,country),name:x.artistName,type:'Artist',disambiguation:x.primaryGenreName||'',genres:[x.primaryGenreName].filter(Boolean),score:90,provider:'itunes',sourceLabels:['Apple iTunes'],sourceUrl:x.artistLinkUrl||x.artistViewUrl||''}));if(kind==='album')return rows.filter(x=>x.collectionId&&x.collectionName&&same(x.artistName,artist)).map(x=>({id:eid('album',x.collectionId,country),title:x.collectionName,type:x.collectionType||'Album',firstReleaseDate:(x.releaseDate||'').slice(0,10),artist:x.artistName||artist,genre:x.primaryGenreName||'',score:90,provider:'itunes',sourceLabels:['Apple iTunes'],sourceUrl:x.collectionViewUrl||''}));return rows.filter(x=>x.trackId&&x.trackName&&same(x.artistName,artist)).map(x=>({id:eid('track',x.trackId,country),title:x.trackName,lengthMs:x.trackTimeMillis||0,artist:x.artistName||artist,genre:x.primaryGenreName||'',score:90,provider:'itunes',sourceLabels:['Apple iTunes'],sourceUrl:x.trackViewUrl||'',releases:x.collectionName?[{id:eid('album',x.collectionId,country),title:x.collectionName,date:(x.releaseDate||'').slice(0,10),status:'Official'}]:[]}));}
async function releases(id,name=''){let {country,id:raw}=pid(id);if(!/^\d+$/.test(raw)){const a=(await search('artist',name||raw))[0];if(!a)return [];({country,id:raw}=pid(a.id));}const {d,country:used}=await ijson('/lookup',{id:raw,entity:'album',limit:'200'},[country,'JP','US'].filter((x,i,a)=>a.indexOf(x)===i));return (d.results||[]).filter(x=>x.wrapperType==='collection'&&x.collectionId).map(x=>({id:eid('album',x.collectionId,used),title:x.collectionName,type:x.collectionType||'Album',firstReleaseDate:(x.releaseDate||'').slice(0,10),secondaryTypes:[],artist:x.artistName||name,genre:x.primaryGenreName||'',provider:'itunes',sourceLabels:['Apple iTunes'],sourceUrl:x.collectionViewUrl||''}));}
async function tracks(id,title='',artist=''){let {country,id:raw}=pid(id);if(!/^\d+$/.test(raw)){const a=(await search('album',title,artist))[0];if(!a)return {release:null,tracks:[]};({country,id:raw}=pid(a.id));}const {d,country:used}=await ijson('/lookup',{id:raw,entity:'song',limit:'200'},[country,'JP','US'].filter((x,i,a)=>a.indexOf(x)===i));const rows=d.results||[],col=rows.find(x=>x.wrapperType==='collection')||{};return {release:{id:eid('album',raw,used),title:col.collectionName||title,date:(col.releaseDate||'').slice(0,10),artist:col.artistName||artist,provider:'itunes'},tracks:rows.filter(x=>x.wrapperType==='track'&&x.kind==='song').map((x,i)=>({id:eid('track',x.trackId,used),title:x.trackName,lengthMs:x.trackTimeMillis||0,position:x.trackNumber||i+1,medium:x.discNumber||1,artist:x.artistName||artist,genre:x.primaryGenreName||'',provider:'itunes'}))};}
async function meta(id,name=''){let {country,id:raw}=pid(id);if(!/^\d+$/.test(raw)){const a=(await search('artist',name||raw))[0];if(!a)return {genres:[],tags:[]};({country,id:raw}=pid(a.id));}const {d}=await ijson('/lookup',{id:raw,entity:'musicArtist'},[country,'JP','US'].filter((x,i,a)=>a.indexOf(x)===i));const r=(d.results||[]).find(x=>x.wrapperType==='artist')||{};return {genres:[r.primaryGenreName].filter(Boolean),tags:[]};}
async function api(req,res,u){if(!rate(req))return json(res,429,{error:'Too many requests'});const q=clean(u.searchParams.get('q')),artist=clean(u.searchParams.get('artist'));if(u.pathname==='/api/health')return json(res,200,{ok:true,version:'0.6.0-beta.2',publicWeb:true,environment:'staging',allowedProviders:['itunes','wikidata']});if(u.pathname==='/api/artist-search')return json(res,200,{artists:await search('artist',q),_meta:{providers:['itunes']}});if(u.pathname==='/api/album-search')return json(res,200,{releaseGroups:await search('album',q,artist),_meta:{providers:['itunes']}});if(u.pathname==='/api/recording-search')return json(res,200,{recordings:await search('track',q,artist),_meta:{providers:['itunes']}});let m=u.pathname.match(/^\/api\/artist\/([^/]+)\/meta$/);if(m)return json(res,200,await meta(decodeURIComponent(m[1]),clean(u.searchParams.get('name'))));m=u.pathname.match(/^\/api\/artist\/([^/]+)\/releases$/);if(m)return json(res,200,{releaseGroups:await releases(decodeURIComponent(m[1]),clean(u.searchParams.get('name')))});m=u.pathname.match(/^\/api\/release-group\/([^/]+)\/tracks$/);if(m){const d=await tracks(decodeURIComponent(m[1]),clean(u.searchParams.get('title')),artist);return json(res,d.tracks.length?200:404,d.tracks.length?d:{...d,error:'収録曲を取得できませんでした。'});}return json(res,404,{error:'Not found'});}
async function serve(res,pathname){if(pathname==='/robots.txt'){const b='User-agent: *\nDisallow: /\n';res.writeHead(200,headers({'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}));return res.end(b);}let rel=decodeURIComponent(pathname==='/'?'/index.html':pathname);if(rel.includes('..')){res.writeHead(400,headers());return res.end('Bad Request');}const f=path.resolve(ROOT,'.'+rel);if(!f.startsWith(ROOT+path.sep)){res.writeHead(403,headers());return res.end('Forbidden');}try{const b=await fs.readFile(f),ext=path.extname(f);const cache=['.js','.css','.svg'].includes(ext)?'public, max-age=300':'no-store';res.writeHead(200,headers({'Content-Type':MIME[ext]||'application/octet-stream','Cache-Control':cache}));res.end(b);}catch{res.writeHead(404,headers({'Cache-Control':'no-store'}));res.end('Not Found');}}
const server=http.createServer(async(req,res)=>{try{if((req.url||'').length>MAX_URL)return json(res,414,{error:'URI Too Long'});const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/'))return await api(req,res,u);await serve(res,u.pathname);}catch(e){console.error(e);json(res,500,{error:'Internal server error'});}});
server.listen(PORT,HOST,()=>console.log(`ARTIST LIVE SHEET staging on ${HOST}:${PORT}`));
